#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  This wizard tells you exactly what to click/type and captures the\n' "$DIM"
  printf '  values along the way. Stop any time with Ctrl-C and re-run later.%s\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"
ICLOUD_TOML="data/icloud.toml"

banner "Connect iCloud calendar (issue #33)"

# ── Stage 1: grant macOS permissions ───────────────────────────────────────
stage "Grant Calendar & Reminders access"
say "The 'tomorrow calendars' command talks to macOS EventKit directly. The"
say "first time it runs, macOS pops up permission dialogs for Calendar and"
say "Reminders access for this terminal app. Only you can click Allow."
note "(Dependencies are already installed via 'uv sync' — nothing to do there.)"
step "We'll run 'tomorrow calendars' now. When the permission dialogs appear,"
step "click Allow for both Calendar and Reminders."
pause "Press Enter to run it now"
uv run tomorrow calendars || true
say ""
if ! confirm "Did you see your calendar and reminder-list names printed above?"; then
  warn "No names showed up. This usually means permission wasn't granted yet."
  step "Open System Settings → Privacy & Security → Calendars, enable it for"
  step "your terminal app (Terminal/iTerm/etc.), then do the same under Reminders."
  open_url "x-apple.systempreferences:com.apple.preference.security?Privacy_Calendars"
  pause "Once enabled, press Enter to try again"
  uv run tomorrow calendars || true
fi

# ── Stage 2: pick which calendars/lists to import ──────────────────────────
stage "Choose calendars and reminder lists to import"
say "Look at the names printed in the previous stage."
step "Type the calendar names you want imported as Anchors, comma-separated"
step "(e.g. Home,Work). Leave blank to import none."
ask ICLOUD_CALENDARS "Calendars:"
step "Type the reminder list names you want imported as Drafts, comma-separated"
step "(e.g. Reminders). Leave blank to import none."
ask ICLOUD_REMINDER_LISTS "Reminder lists:"

# ── Stage 3: write data/icloud.toml ─────────────────────────────────────────
stage "Write data/icloud.toml"

_toml_array() {
  local input="$1" IFS=',' name trimmed out=() parts=()
  if [[ -n "$input" ]]; then
    read -ra parts <<< "$input"
  fi
  for name in "${parts[@]+"${parts[@]}"}"; do
    trimmed="$(printf '%s' "$name" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
    [[ -n "$trimmed" ]] && out+=("\"$trimmed\"")
  done
  local joined=""
  for i in "${!out[@]+"${!out[@]}"}"; do
    [[ $i -gt 0 ]] && joined+=", "
    joined+="${out[$i]}"
  done
  printf '[%s]' "$joined"
}

CALENDARS_TOML="$(_toml_array "$ICLOUD_CALENDARS")"
REMINDER_LISTS_TOML="$(_toml_array "$ICLOUD_REMINDER_LISTS")"

cat > "$ICLOUD_TOML" <<EOF
calendars = $CALENDARS_TOML
reminder_lists = $REMINDER_LISTS_TOML
EOF

printf '  %s✓ wrote%s %s\n' "$GREEN" "$RESET" "$ICLOUD_TOML"
note "$(cat "$ICLOUD_TOML")"
say ""
say "From now on, creating a new day's Session will import matching events"
say "as Anchors and matching reminders as Drafts, tagged with a 📅 iCloud badge."
say "This never re-triggers on Reset/Undo/Redo — only on brand-new Sessions."

finish
